name: CI / CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    name: Laravel Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Execute backend tests
        run: ./vendor/bin/pest

      - name: Install NPM dependencies
        run: yarn install --non-interactive

      - name: Compile assets
        run: yarn run production

      - name: Execute E2E tests
        uses: cypress-io/github-action@v1
        with:
          browser: chrome

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_LOGIN }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG }} .
          echo ${{ secrets.DOCKER_PWD  }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
          docker push ${{ secrets.DOCKER_LOGIN }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG }}

      - name: Deploy app to Server via Docker
        run: echo 'LOL'
